name: Update and publish crate

# Controls when the workflow will run
on:
  schedule:
    - cron: '0 14 * * 1'

  workflow_dispatch:


jobs:
  update_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup git
        run: |
              git config --local user.email "action@github.com"
              git config --local user.name "GitHub Action"
      - name: Update toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Update 3bc and crate
        run: ./util/update.sh
      - name: Push changes
        run: git push
      - name: Publish changes
        uses: katyo/publish-crates@v1
         with:
          registry-token: ${{ secrets.CARGO_TOKEN }}
          ignore-unpublished-changes: true
